### ISSUE TITLE
ascua doc wesite is not accessible 

### ISSUE THREAD

**Issue by amiarSlimane** [surrealdb/ascua#4]
can't access https://abcum.github.io/ascua , showing 404 page not found

**Comment by naisofly** [comment]
@amiarSlimane the docs are now available at [https://surrealdb.github.io/ascua](https://surrealdb.github.io/ascua)

**Comment by akankshadharkar** [comment]
Thanks for pointing this out @amiarSlimane. I'll get it updated.

**Comment by tobiemh** [comment]
This should be fixed now ✅ !
